### PR TITLE
[CV-422] [Mobile] Added Annual Financial Report

### PR DESCRIPTION
**Pull request by justncheng**
Clickup Link: https://app.clickup.com/t/86azdbp05

### Description:

As a condo management company mobile user, I want to see what payments my tenants have paid, and see how much is owed to me at the end of the year.

This allows the condo management company view everything that a user has paid for each individual condo.

### Demo:

image

### CODE REVIEW

**Review by Adissuu — DISMISSED** [review]
Good job!

**Review by Fetyali7 — DISMISSED** [review]
I think a bit more comment is needed explaining the code but other than that, it looks good to me!

**Comment by justncheng** [comment]
> I think a bit more comment is needed explaining the code but other than that, it looks good to me!

Sounds good will do

**Review by Fetyali7 — APPROVED** [review]
Looks good!

**Review by XavierGuertin — APPROVED** [review]

**Review by XavierGuertin — CHANGES_REQUESTED** [review]
add some comments at the top of the class explaining what it does

**Review by justncheng — COMMENTED** [review]
complete

**Review by justncheng — COMMENTED** [review]
p

**Review by XavierGuertin — APPROVED** [review]

**Review by LiamDaigle — APPROVED** [review]
lgtm!

**Pull request merged**
