### PR TITLE
[CV-421] Added Financial Status to Web

### PR DESCRIPTION
**Pull request by LiamDaigle**
Clickup Issue: https://app.clickup.com/t/86azdbnxu
Added the Financial Payment status and History into the web.
Also added the condo units into each property.

Before clicking on a condo unit:
image
After clicking on a condo unit:
image

### CODE REVIEW

**Review by yasminehilout — APPROVED** [review]
Lgtm! 
Thank you!

**Review by XavierGuertin — DISMISSED** [review]

**Review by XavierGuertin — CHANGES_REQUESTED** [review]
Vercel not passing.

**Comment by LiamDaigle** [comment]
> Vercel not passing.

Fixed

**Review by XavierGuertin — APPROVED** [review]

**Review by lo-vil — APPROVED** [review]
Let's get this bread

**Pull request merged**
